### ISSUE TITLE
error db (yii\db\Exception: SQLSTATE[HY000]: General error: 1096 No tables used) 

### ISSUE THREAD

**Issue by tecnoterabyte** [yiisoft/db#1]
| Q                | A
| ---------------- | ---
| Yii version      | 3.0
| PHP version      | 7.1.17
| Operating system | Centos 7

```
Next yii\db\Exception: SQLSTATE[HY000]: General error: 1096 No tables used
The SQL being executed was: SELECT * in /home/example.com/public_html/vendor/yiisoft/db/src/Schema.php:664

Stack trace:
#0 /home/example.com/public_html/vendor/yiisoft/db/src/Command.php(1263): yii\db\Schema->convertException(Object(PDOException), 'SELECT *')
#1 /home/example.com/public_html/vendor/yiisoft/db/src/Command.php(1148): yii\db\Command->internalExecute('SELECT *')
#2 /home/example.com/public_html/vendor/yiisoft/db/src/Command.php(413): yii\db\Command->queryInternal('fetch', NULL)
#3 /home/example.com/public_html/vendor/yiisoft/db/src/Query.php(274): yii\db\Command->queryOne()
#4 /home/example.com/public_html/vendor/yiisoft/active-record/src/ActiveQuery.php(294): yii\db\Query->one(NULL)
#5 /home/example.com/public_html/vendor/yiisoft/active-record/src/BaseActiveRecord.php(111): yii\activerecord\ActiveQuery->one()
#6 /home/example.com/public_html/vendor/yiisoft/yii-base-web/src/models/User.php(83): yii\activerecord\BaseActiveRecord::findOne(Array)
#7 /home/example.com/public_html/vendor/yiisoft/yii-base-web/src/forms/LoginForm.php(77): yii\app\models\User::findByUsername('admin')
#8 /home/example.com/public_html/vendor/yiisoft/yii-base-web/src/forms/LoginForm.php(49): yii\app\forms\LoginForm->getUser()
#9 [internal function]: yii\app\forms\LoginForm->validatePassword('password', NULL, Object(yii\validators\InlineValidator))
#10 /home/example.com/public_html/vendor/yiisoft/core/src/validators/InlineValidator.php(72): call_user_func(Array, 'password', NULL, Object(yii\validators\InlineValidator))
#11 /home/example.com/public_html/vendor/yiisoft/core/src/validators/Validator.php(274): yii\validators\InlineValidator->validateAttribute(Object(yii\app\forms\LoginForm), 'password')
#12 /home/example.com/public_html/vendor/yiisoft/core/src/base/Model.php(364): yii\validators\Validator->validateAttributes(Object(yii\app\forms\LoginForm), Array)
#13 /home/example.com/public_html/vendor/yiisoft/yii-base-web/src/forms/LoginForm.php(63): yii\base\Model->validate()
#14 /home/example.com/public_html/vendor/yiisoft/yii-base-web/src/controllers/SiteController.php(78): yii\app\forms\LoginForm->login()
#15 /home/example.com/public_html/vendor/yiisoft/core/src/base/InlineAction.php(57): yii\app\controllers\SiteController->actionLogin()
#16 /home/example.com/public_html/vendor/yiisoft/core/src/base/Controller.php(160): yii\base\InlineAction->runWithParams(Array)
#17 /home/example.com/public_html/vendor/yiisoft/core/src/base/Module.php(542): yii\base\Controller->runAction('login', Array)
#18 /home/example.com/public_html/vendor/yiisoft/yii-web/src/Application.php(94): yii\base\Module->runAction('site/login', Array)
#19 /home/example.com/public_html/vendor/yiisoft/core/src/base/Application.php(525): yii\web\Application->handleRequest(Object(yii\web\Request))
#20 /home/example.com/public_html/public/index.php(14): yii\base\Application->run()
#21 /home/example.com/public_html/public/index.php(15): {closure}()
#22 {main}
Additional Information:
Array
(
    [0] => HY000
    [1] => 1096
    [2] => No tables used
)

2018-09-09 01:08:28 [190.142.101.156][-][e05d5532cdeea664670fa57b4ff9aec5][info][application] $_GET = []

$_POST = [
    '_csrf' => 'MuZl0hEYOz8SIZw_V_qcjAPKtCe29HHIo0h-i56owFYHhTqVXl5NVyVV31Y7nfrHcY_7YumBJKTqPgrZ9M32Ow=='
    'LoginForm' => [
        'username' => 'admin'
        'password' => 'admin'
        'rememberMe' => '1'
    ]
    'login-button' => ''
]
```

**Comment by marcelodeandrade** [comment]
How are you making the call? This does not seem to be an error from db component.

**Comment by tecnoterabyte** [comment]
hello @hiqsol  I know this is not a priority there is some missing configuration, there is a way to solve it I would appreciate your comment,

Greetings.

**Comment by terabytesoftw** [comment]
We hope that as a Christmas gift we have the connection of the database ready to be able to continue advancing.

**Comment by hiqsol** [comment]
Please give instruction how to reproduce it.

**Comment by terabytesoftw** [comment]
In the yii-base-web if you enable in the view to login in the application, when you click throws this exception.

```
**Config DB:**
    /config/params.php
	'db.dsn'        => 'mysql:host=127.0.0.1;dbname=app_backup;charset=utf8',
	'db.username'   => 'app_web',
	'db.password'   => 'app_password',

PDOException: SQLSTATE[HY000]: General error: 1096 No tables used in /home/app.web/public_html/vendor/yiisoft/db/src/Command.php:1258
Stack trace:

#0 /home/app.web/public_html/vendor/yiisoft/db/src/Command.php(1258): PDOStatement->execute()
#1 /home/app.web/public_html/vendor/yiisoft/db/src/Command.php(1148): yii\db\Command->internalExecute('SELECT *')
#2 /home/app.web/public_html/vendor/yiisoft/db/src/Command.php(413): yii\db\Command->queryInternal('fetch', NULL)
#3 /home/app.web/public_html/vendor/yiisoft/db/src/Query.php(274): yii\db\Command->queryOne()
#4 /home/app.web/public_html/vendor/yiisoft/active-record/src/ActiveQuery.php(294): yii\db\Query->one(NULL)
#5 /home/app.web/public_html/vendor/yiisoft/active-record/src/BaseActiveRecord.php(111): yii\activerecord\ActiveQuery->one()
#6 /home/app.web/public_html/vendor/yiisoft/yii-base-web/src/models/User.php(83): yii\activerecord\BaseActiveRecord::findOne(Array)
#7 /home/app.web/public_html/vendor/yiisoft/yii-base-web/src/forms/LoginForm.php(77): yii\app\models\User::findByUsername('tecnologiaterab...')
#8 /home/app.web/public_html/vendor/yiisoft/yii-base-web/src/forms/LoginForm.php(49): yii\app\forms\LoginForm->getUser()
#9 [internal function]: yii\app\forms\LoginForm->validatePassword('password', NULL, Object(yii\validators\InlineValidator))
#10 /home/app.web/public_html/vendor/yiisoft/yii-core/src/validators/InlineValidator.php(72): call_user_func(Array, 'password', NULL, Object(yii\validators\InlineValidator))
#11 /home/app.web/public_html/vendor/yiisoft/yii-core/src/validators/Validator.php(274): yii\validators\InlineValidator->validateAttribute(Object(yii\app\forms\LoginForm), 'password')
#12 /home/app.web/public_html/vendor/yiisoft/yii-core/src/base/Model.php(364): yii\validators\Validator->validateAttributes(Object(yii\app\forms\LoginForm), Array)
#13 /home/app.web/public_html/vendor/yiisoft/yii-base-web/src/forms/LoginForm.php(63): yii\base\Model->validate()
#14 /home/app.web/public_html/vendor/yiisoft/yii-base-web/src/controllers/SiteController.php(87): yii\app\forms\LoginForm->login()
#15 /home/app.web/public_html/vendor/yiisoft/yii-core/src/base/InlineAction.php(56): yii\app\controllers\SiteController->actionLogin()
#16 /home/app.web/public_html/vendor/yiisoft/yii-core/src/base/Controller.php(160): yii\base\InlineAction->runWithParams(Array)
#17 /home/app.web/public_html/vendor/yiisoft/yii-core/src/base/Module.php(542): yii\base\Controller->runAction('login', Array)
#18 /home/app.web/public_html/vendor/yiisoft/yii-web/src/Application.php(94): yii\base\Module->runAction('site/login', Array)
#19 /home/app.web/public_html/vendor/yiisoft/yii-core/src/base/Application.php(544): yii\web\Application->handleRequest(Object(yii\web\Request))
#20 /home/app.web/public_html/public/index.php(14): yii\base\Application->run()
#21 /home/app.web/public_html/public/index.php(15): {closure}()
#22 {main}

Next yii\db\Exception: SQLSTATE[HY000]: General error: 1096 No tables used
The SQL being executed was: SELECT * in /home/app.web/public_html/vendor/yiisoft/db/src/Schema.php:664
Stack trace:

#0 /home/app.web/public_html/vendor/yiisoft/db/src/Command.php(1263): yii\db\Schema->convertException(Object(PDOException), 'SELECT *')
#1 /home/app.web/public_html/vendor/yiisoft/db/src/Command.php(1148): yii\db\Command->internalExecute('SELECT *')
#2 /home/app.web/public_html/vendor/yiisoft/db/src/Command.php(413): yii\db\Command->queryInternal('fetch', NULL)
#3 /home/app.web/public_html/vendor/yiisoft/db/src/Query.php(274): yii\db\Command->queryOne()
#4 /home/app.web/public_html/vendor/yiisoft/active-record/src/ActiveQuery.php(294): yii\db\Query->one(NULL)
#5 /home/app.web/public_html/vendor/yiisoft/active-record/src/BaseActiveRecord.php(111): yii\activerecord\ActiveQuery->one()
#6 /home/app.web/public_html/vendor/yiisoft/yii-base-web/src/models/User.php(83): yii\activerecord\BaseActiveRecord::findOne(Array)
#7 /home/app.web/public_html/vendor/yiisoft/yii-base-web/src/forms/LoginForm.php(77): yii\app\models\User::findByUsername('tecnologiaterab...')
#8 /home/app.web/public_html/vendor/yiisoft/yii-base-web/src/forms/LoginForm.php(49): yii\app\forms\LoginForm->getUser()
#9 [internal function]: yii\app\forms\LoginForm->validatePassword('password', NULL, Object(yii\validators\InlineValidator))
#10 /home/app.web/public_html/vendor/yiisoft/yii-core/src/validators/InlineValidator.php(72): call_user_func(Array, 'password', NULL, Object(yii\validators\InlineValidator))
#11 /home/app.web/public_html/vendor/yiisoft/yii-core/src/validators/Validator.php(274): yii\validators\InlineValidator->validateAttribute(Object(yii\app\forms\LoginForm), 'password')
#12 /home/app.web/public_html/vendor/yiisoft/yii-core/src/base/Model.php(364): yii\validators\Validator->validateAttributes(Object(yii\app\forms\LoginForm), Array)
#13 /home/app.web/public_html/vendor/yiisoft/yii-base-web/src/forms/LoginForm.php(63): yii\base\Model->validate()
#14 /home/app.web/public_html/vendor/yiisoft/yii-base-web/src/controllers/SiteController.php(87): yii\app\forms\LoginForm->login()
#15 /home/app.web/public_html/vendor/yiisoft/yii-core/src/base/InlineAction.php(56): yii\app\controllers\SiteController->actionLogin()
#16 /home/app.web/public_html/vendor/yiisoft/yii-core/src/base/Controller.php(160): yii\base\InlineAction->runWithParams(Array)
#17 /home/app.web/public_html/vendor/yiisoft/yii-core/src/base/Module.php(542): yii\base\Controller->runAction('login', Array)
#18 /home/app.web/public_html/vendor/yiisoft/yii-web/src/Application.php(94): yii\base\Module->runAction('site/login', Array)
#19 /home/app.web/public_html/vendor/yiisoft/yii-core/src/base/Application.php(544): yii\web\Application->handleRequest(Object(yii\web\Request))
#20 /home/app.web/public_html/public/index.php(14): yii\base\Application->run()
#21 /home/app.web/public_html/public/index.php(15): {closure}()
#22 {main}

Additional Information:
Array
(
    [0] => HY000
    [1] => 1096
    [2] => No tables used
)

**Comment by terabytesoftw** [comment]
Checking well @hiqsol the problem is in the active-record, ActiveRecord.php loads the schema correctly, but in ActiveQuery.php does not load the connection, so I'll close the problem and open it in active-record.
