### ISSUE TITLE
Circular Reference to schema

### ISSUE THREAD

**Issue by axtho** [yiisoft/db#31]
On downloading the current master branch and installing everything, I get this following error on access of `/public/:`

```
[05-Sep-2018 07:41:16 UTC] An Error occurred while handling another error:
yii\di\exceptions\CircularReferenceException: Circular reference to "yii\db\mysql\Schema" detected while building: yii\db\mysql\Schema; dereferencing:  in /Applications/MAMP/htdocs/hack/y3/vendor/yiisoft/di/src/AbstractContainer.php:121
Stack trace:
#0 /Applications/MAMP/htdocs/hack/y3/vendor/yiisoft/di/src/Factory.php(48): yii\di\AbstractContainer->build('yii\\db\\mysql\\Sc...', Array)
#1 /Applications/MAMP/htdocs/hack/y3/vendor/yiisoft/core/src/helpers/BaseYii.php(69): yii\di\Factory->create(Array, Array)
#2 /Applications/MAMP/htdocs/hack/y3/vendor/yiisoft/db/src/Connection.php(841): yii\helpers\BaseYii::createObject(Array)
#3 /Applications/MAMP/htdocs/hack/y3/vendor/yiisoft/active-record/src/ActiveRecord.php(391): yii\db\Connection->getSchema()
#4 /Applications/MAMP/htdocs/hack/y3/vendor/yiisoft/active-record/src/ActiveRecord.php(216): yii\activerecord\ActiveRecord::getTableSchema()
#5 /Applications/MAMP/htdocs/hack/y3/vendor/yiisoft/active-record/src/ActiveRecord.php(195): yii\activerecord\ActiveRecord::filterCondition(Array)
#6 /Applications/MAMP/htdocs/hack/y3/vendor/yiisoft/active-record/src/BaseActiveRecord.php(111): yii\activerecord\ActiveRecord::findByCondition(Array)
#7 /Applications/MAMP/htdocs/hack/y3/vendor/yiisoft/yii-base-web/src/models/User.php(64): yii\activerecord\BaseActiveRecord::findOne(Array)
#8 /Applications/MAMP/htdocs/hack/y3/vendor/yiisoft/yii-web/src/User.php(675): yii\app\models\User::findIdentity(1)
#9 /Applications/MAMP/htdocs/hack/y3/vendor/yiisoft/yii-web/src/User.php(195): yii\web\User->renewAuthStatus()
#10 /Applications/MAMP/htdocs/hack/y3/vendor/yiisoft/yii-web/src/User.php(363): yii\web\User->getIdentity()
#11 /Applications/MAMP/htdocs/hack/y3/vendor/yiisoft/core/src/base/Component.php(142): yii\web\User->getIsGuest()
#12 /Applications/MAMP/htdocs/hack/y3/vendor/yiisoft/yii-base-web/src/views/layouts/main.php(44): yii\base\Component->__get('isGuest')
#13 /Applications/MAMP/htdocs/hack/y3/vendor/yiisoft/view/src/view/View.php(324): require('/Applications/M...')
#14 /Applications/MAMP/htdocs/hack/y3/vendor/yiisoft/view/src/view/View.php(246): yii\view\View->renderPhpFile('/Applications/M...', Array)
#15 /Applications/MAMP/htdocs/hack/y3/vendor/yiisoft/core/src/base/Controller.php(397): yii\view\View->renderFile('/Applications/M...', Array, Object(yii\app\controllers\SiteController))
#16 /Applications/MAMP/htdocs/hack/y3/vendor/yiisoft/core/src/base/Controller.php(383): yii\base\Controller->renderContent('<div class="sit...')
#17 /Applications/MAMP/htdocs/hack/y3/vendor/yiisoft/yii-web/src/ErrorAction.php(173): yii\base\Controller->render('error', Array)
#18 /Applications/MAMP/htdocs/hack/y3/vendor/yiisoft/yii-web/src/ErrorAction.php(152): yii\web\ErrorAction->renderHtmlResponse()
#19 /Applications/MAMP/htdocs/hack/y3/vendor/yiisoft/core/src/base/Action.php(99): yii\web\ErrorAction->run()
#20 /Applications/MAMP/htdocs/hack/y3/vendor/yiisoft/core/src/base/Controller.php(160): yii\base\Action->runWithParams(Array)
#21 /Applications/MAMP/htdocs/hack/y3/vendor/yiisoft/core/src/base/Module.php(542): yii\base\Controller->runAction('error', Array)
#22 /Applications/MAMP/htdocs/hack/y3/vendor/yiisoft/yii-web/src/ErrorHandler.php(103): yii\base\Module->runAction('site/error')
#23 /Applications/MAMP/htdocs/hack/y3/vendor/yiisoft/core/src/base/ErrorHandler.php(123): yii\web\ErrorHandler->renderException(Object(yii\di\exceptions\NotFoundException))
#24 [internal function]: yii\base\ErrorHandler->handleException(Object(yii\di\exceptions\NotFoundException))
#25 {main}
Previous exception:
yii\di\exceptions\NotFoundException: No definition for "yii\db\mysql\Schema" found in /Applications/MAMP/htdocs/hack/y3/vendor/yiisoft/di/src/AbstractContainer.php:161
Stack trace:
#0 /Applications/MAMP/htdocs/hack/y3/vendor/yiisoft/di/src/AbstractContainer.php(134): yii\di\AbstractContainer->buildWithoutDefinition('yii\\db\\mysql\\Sc...', Array)
#1 /Applications/MAMP/htdocs/hack/y3/vendor/yiisoft/di/src/AbstractContainer.php(155): yii\di\AbstractContainer->build('yii\\db\\mysql\\Sc...', Array)
#2 /Applications/MAMP/htdocs/hack/y3/vendor/yiisoft/di/src/AbstractContainer.php(134): yii\di\AbstractContainer->buildWithoutDefinition('yii\\db\\mysql\\Sc...', Array)
#3 /Applications/MAMP/htdocs/hack/y3/vendor/yiisoft/di/src/Factory.php(48): yii\di\AbstractContainer->build('yii\\db\\mysql\\Sc...', Array)
#4 /Applications/MAMP/htdocs/hack/y3/vendor/yiisoft/core/src/helpers/BaseYii.php(69): yii\di\Factory->create(Array, Array)
#5 /Applications/MAMP/htdocs/hack/y3/vendor/yiisoft/db/src/Connection.php(841): yii\helpers\BaseYii::createObject(Array)
#6 /Applications/MAMP/htdocs/hack/y3/vendor/yiisoft/active-record/src/ActiveRecord.php(391): yii\db\Connection->getSchema()
#7 /Applications/MAMP/htdocs/hack/y3/vendor/yiisoft/active-record/src/ActiveRecord.php(216): yii\activerecord\ActiveRecord::getTableSchema()
#8 /Applications/MAMP/htdocs/hack/y3/vendor/yiisoft/active-record/src/ActiveRecord.php(195): yii\activerecord\ActiveRecord::filterCondition(Array)
#9 /Applications/MAMP/htdocs/hack/y3/vendor/yiisoft/active-record/src/BaseActiveRecord.php(111): yii\activerecord\ActiveRecord::findByCondition(Array)
#10 /Applications/MAMP/htdocs/hack/y3/vendor/yiisoft/yii-base-web/src/models/User.php(64): yii\activerecord\BaseActiveRecord::findOne(Array)
#11 /Applications/MAMP/htdocs/hack/y3/vendor/yiisoft/yii-web/src/User.php(675): yii\app\models\User::findIdentity(1)
#12 /Applications/MAMP/htdocs/hack/y3/vendor/yiisoft/yii-web/src/User.php(195): yii\web\User->renewAuthStatus()
#13 /Applications/MAMP/htdocs/hack/y3/vendor/yiisoft/yii-web/src/User.php(363): yii\web\User->getIdentity()
#14 /Applications/MAMP/htdocs/hack/y3/vendor/yiisoft/core/src/base/Component.php(142): yii\web\User->getIsGuest()
#15 /Applications/MAMP/htdocs/hack/y3/vendor/yiisoft/yii-base-web/src/views/layouts/main.php(44): yii\base\Component->__get('isGuest')
#16 /Applications/MAMP/htdocs/hack/y3/vendor/yiisoft/view/src/view/View.php(324): require('/Applications/M...')
#17 /Applications/MAMP/htdocs/hack/y3/vendor/yiisoft/view/src/view/View.php(246): yii\view\View->renderPhpFile('/Applications/M...', Array)
#18 /Applications/MAMP/htdocs/hack/y3/vendor/yiisoft/core/src/base/Controller.php(397): yii\view\View->renderFile('/Applications/M...', Array, Object(yii\app\controllers\SiteController))
#19 /Applications/MAMP/htdocs/hack/y3/vendor/yiisoft/core/src/base/Controller.php(383): yii\base\Controller->renderContent('<div class="sit...')
#20 /Applications/MAMP/htdocs/hack/y3/vendor/yiisoft/yii-base-web/src/controllers/SiteController.php(63): yii\base\Controller->render('index')
#21 /Applications/MAMP/htdocs/hack/y3/vendor/yiisoft/core/src/base/InlineAction.php(57): yii\app\controllers\SiteController->actionIndex()
#22 /Applications/MAMP/htdocs/hack/y3/vendor/yiisoft/core/src/base/Controller.php(160): yii\base\InlineAction->runWithParams(Array)
#23 /Applications/MAMP/htdocs/hack/y3/vendor/yiisoft/core/src/base/Module.php(542): yii\base\Controller->runAction('', Array)
#24 /Applications/MAMP/htdocs/hack/y3/vendor/yiisoft/yii-web/src/Application.php(94): yii\base\Module->runAction('', Array)
#25 /Applications/MAMP/htdocs/hack/y3/vendor/yiisoft/core/src/base/Application.php(525): yii\web\Application->handleRequest(Object(yii\web\Request))
#26 /Applications/MAMP/htdocs/hack/y3/public/index.php(14): yii\base\Application->run()
#27 /Applications/MAMP/htdocs/hack/y3/public/index.php(15): {closure}()
#28 {main}
```

**Comment by terabytesoftw** [comment]
Fixed.
